"""add_reviews_table

Revision ID: f2a9dadc716a
Revises: fffcc21cbe39
Create Date: 2025-07-29 18:55:04.278273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'f2a9dadc716a'
down_revision: Union[str, Sequence[str], None] = 'fffcc21cbe39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goal_progress_id', table_name='goal_progress')
    op.drop_table('goal_progress')
    op.alter_column('goals', 'progress',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('((0.00))'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'progress',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('((0.00))'))
    op.create_table('goal_progress',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_percentage', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('comments', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', mssql.DATETIMEOFFSET(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name='FK__goal_prog__goal___5DCAEF64'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__goal_prog__user___5EBF139D'),
    sa.PrimaryKeyConstraint('id', name='PK__goal_pro__3213E83F3DB2BC70')
    )
    op.create_index('ix_goal_progress_id', 'goal_progress', ['id'], unique=False)
    # ### end Alembic commands ###
