server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: warehouse-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/warehouses/**
        - id: po-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/purchase-orders/**
        - id: supplier-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/suppliers/**
        - id: alert-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/alerts/**
        - id: reporting-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/reports/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true 

jwt:
  secret: "QwErTyUiOpAsDfGhJkLzXcVbNm1234567890abcd" 