server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: postgres
    password: Jeya@105637
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
logging:
  level:
    org.springframework: INFO
    com.yourapp: DEBUG 
jwt:
  secret: QwErTyUiOpAsDfGhJkLzXcVbNm1234567890abcd 